<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Photo_Tools</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <COMReference Include="{d37e2a3e-8545-3a39-9f4f-31827c9124ab}">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>4</VersionMinor>
      <VersionMajor>2</VersionMajor>
      <Guid>d37e2a3e-8545-3a39-9f4f-31827c9124ab</Guid>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MetadataExtractor" Version="2.8.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.3" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.7" />
    <PackageReference Include="XmpCore" Version="6.1.10.1" />
  </ItemGroup>

</Project>
